.benchmark_mluq_on_horeka:
  extends: .benchmark_on_horeka
  variables:
    USE_MPP_DATA: 'true'
    USE_LSDF: 'false'
    WTIME: '00:05:00'
    PROCS: '32'
    LABEL: ''
    NODES: ''
    CONFIG: ''
    CMAKE_ARGS: '-DBUILD_TESTS=OFF -DSPACE_DIM=2 -DBUILD_TUTORIAL=ON -DBUILD_TUTORIAL_TESTS=OFF -DBUILD_UQ=ON -DBUILD_UQ_TESTS=OFF -DMPP_BUILD_TYPE=MppRelease -DAGGREGATE_FOR_SOLUTION=ON'
    SALLOC: 'salloc -p cpuonly -t $WTIME -N $NODES -n $PROCS mpirun M++ $CONFIG logfile=UseConfigEntries[$LABEL] WTime=$WTIME'
  after_script:
    - cd $(ws_find mpp-build-${CI_JOB_NAME})
    - for jobid in `sacct -P --delimiter=" " | grep ${CI_JOB_NAME}-${CI_PIPELINE_ID} | awk {' print $1 '}`; do seff $jobid; done
    - module load jupyter/base/2023-04-28
    - python3 python/mluqmppy.py --build_dir=mpp-build-${CI_JOB_NAME}
    - cd pipeline
    - ./archive.sh
